//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlikIndomaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockOutLog
    {
        public System.Guid Id { get; set; }
        public string PLU { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> Harga { get; set; }
        public string StoreId { get; set; }
        public Nullable<int> OrderQty { get; set; }
        public Nullable<int> AvailbleQty { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateBy { get; set; }
        public string ProductDescription { get; set; }
        public string ShoppingCartId { get; set; }
        public string SalesOrderNo { get; set; }
    }
}
