//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlikIndomaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> IdRegion { get; set; }
        public string KodeDC { get; set; }
        public string StoreName { get; set; }
        public string StoreKode { get; set; }
    }
}
